version: '3.8'
services:
  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    networks:
      - scaler-network

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    networks:
      - scaler-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    networks:
      - scaler-network

  mysql-user:
    image: mysql:8.0.33
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${USER_DB_NAME}
      MYSQL_USER: ${USER_DB_USER}
      MYSQL_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-user-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - scaler-network

  mysql-product:
    image: mysql:8.0.33
    container_name: mysql-product
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PRODUCT_DB_NAME}
      MYSQL_USER: ${PRODUCT_DB_USER}
      MYSQL_PASSWORD: ${PRODUCT_DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-product-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - scaler-network

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - eureka-server
      - mysql-user
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-user:3306/${USER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${USER_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${USER_DB_PASSWORD}
    networks:
      - scaler-network

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - eureka-server
      - mysql-product
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-product:3306/${PRODUCT_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${PRODUCT_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${PRODUCT_DB_PASSWORD}
    networks:
      - scaler-network

volumes:
  mysql-user-data:
  mysql-product-data:

networks:
  scaler-network:
    driver: bridge